apiVersion: v2
name: cloudreve
version: 0.1.1
kubeVersion: ^1.8.0-0
description: Self-hosted file management and sharing system, supports multiple storage providers.
type: application
home: https://cloudreve.org/
sources:
  - https://github.com/cloudreve/Cloudreve
maintainers:
  - email: david.gheghea@unxwares.com
    name: David Gheghea
icon: https://raw.githubusercontent.com/cloudreve/frontend/master/public/static/img/logo192.png
appVersion: "3.8.0"
