{{- if .Values.createConfigmap }}
{{- $dbType := .Values.database.type -}}
{{- $dbHost := .Values.database.host -}}
{{- $dbPort := .Values.database.port -}}
{{- $dbName := .Values.database.name -}}
{{- $dbUser := .Values.database.user -}}
{{- $dbPassword := .Values.database.password -}}

{{- if .Values.database.existingSecret -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.database.existingSecret -}}
{{- if $secret -}}
{{- $dbType = index $secret.data (.Values.database.existingSecretKeys.type) | b64dec -}}
{{- $dbHost = index $secret.data (.Values.database.existingSecretKeys.host) | b64dec -}}
{{- $dbPort = index $secret.data (.Values.database.existingSecretKeys.port) | b64dec -}}
{{- $dbName = index $secret.data (.Values.database.existingSecretKeys.name) | b64dec -}}
{{- $dbUser = index $secret.data (.Values.database.existingSecretKeys.user) | b64dec -}}
{{- $dbPassword = index $secret.data (.Values.database.existingSecretKeys.password) | b64dec -}}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudreve.fullname" . }}
  namespace: {{ include "cloudreve.namespace" . }}
  labels:
    {{- include "cloudreve.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  conf.ini: |
  {{- range $elem, $elemVal := index .Values "conf.ini" }}
    {{- if not (kindIs "map" $elemVal) }}
    {{- if kindIs "invalid" $elemVal }}
    {{ $elem }} =
    {{- else if kindIs "string" $elemVal }}
    {{ $elem }} = {{ tpl $elemVal $ }}
    {{- else }}
    {{ $elem }} = {{ $elemVal }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- range $key, $value := index .Values "conf.ini" }}
    {{- if kindIs "map" $value }}
    [{{ $key }}]
    {{- range $elem, $elemVal := $value }}
    {{- if kindIs "invalid" $elemVal }}
    {{ $elem }} =
    {{- else if kindIs "string" $elemVal }}
    {{ $elem }} = {{ tpl $elemVal $ }}
    {{- else }}
    {{ $elem }} = {{ $elemVal }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
    [Database]
    Type = {{ $dbType }}
    Host = {{ $dbHost }}
    Port = {{ $dbPort }}
    Name = {{ $dbName }}
    User = {{ $dbUser }}
    Password = {{ $dbPassword }}
{{- end}}
